version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sendy
      MYSQL_USER: sendy
      MYSQL_PASSWORD: sendy

    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  sendy:
    image: smartbrood/sendy
    ports:
      - "80:80"
    volumes:
      - ./docker/sendy/files/config.php:/data/htdocs/sendy/includes/config.php
      - sendy_upload:/data/htdocs/sendy/upload
      - sendy_uploads:/data/htdocs/sendy/uploads
    links:
      - mysql:mysql

volumes:
  mysql_volume:
  sendy_upload:
  sendy_uploads:
